// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHjD4U43N4G_0npu8Ugo-AEK4veZWHeIY',
    appId: '1:354550793280:web:2322752d234e4453c2cba5',
    messagingSenderId: '354550793280',
    projectId: 'qr-assistant-f26b4',
    authDomain: 'qr-assistant-f26b4.firebaseapp.com',
    storageBucket: 'qr-assistant-f26b4.appspot.com',
    measurementId: 'G-D31X5XTK53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQztSb8Gi0G_Eou3Q6I-K-DVIESsiLd_A',
    appId: '1:354550793280:android:502b424941cfe25ec2cba5',
    messagingSenderId: '354550793280',
    projectId: 'qr-assistant-f26b4',
    storageBucket: 'qr-assistant-f26b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYv_7Y-_IpRrjbP1zNLyhKciyV4eEJOEU',
    appId: '1:354550793280:ios:0eaa9ba0addde334c2cba5',
    messagingSenderId: '354550793280',
    projectId: 'qr-assistant-f26b4',
    storageBucket: 'qr-assistant-f26b4.appspot.com',
    iosBundleId: 'com.example.qrAssistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYv_7Y-_IpRrjbP1zNLyhKciyV4eEJOEU',
    appId: '1:354550793280:ios:0eaa9ba0addde334c2cba5',
    messagingSenderId: '354550793280',
    projectId: 'qr-assistant-f26b4',
    storageBucket: 'qr-assistant-f26b4.appspot.com',
    iosBundleId: 'com.example.qrAssistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHjD4U43N4G_0npu8Ugo-AEK4veZWHeIY',
    appId: '1:354550793280:web:abfbf3b7f16bd234c2cba5',
    messagingSenderId: '354550793280',
    projectId: 'qr-assistant-f26b4',
    authDomain: 'qr-assistant-f26b4.firebaseapp.com',
    storageBucket: 'qr-assistant-f26b4.appspot.com',
    measurementId: 'G-5CEJB87X6D',
  );
}
